/*
 * include/linux/mfd/wm8944/pdata.h -- Platform data for WM8944
 *
 * Copyright 2015 Sierra Wireless
 *
 * Author: Jean Michel Chauvet <jchauvet@sierrawireless.com>,
 *         Gaetan Perrier <gperrier@sierrawireless.com>
 *
 * based on include/linux/mfd/wm8994/pdata.h
 *     Copyright 2009 Wolfson Microelectronics PLC.
 *     Author: Mark Brown <broonie@opensource.wolfsonmicro.com>
 *
 *
 *  This program is free software; you can redistribute  it and/or modify it
 *  under  the terms of  the GNU General  Public License as published by the
 *  Free Software Foundation;  either version 2 of the  License, or (at your
 *  option) any later version.
 *
 */

#ifndef __MFD_WM8944_PDATA_H__
#define __MFD_WM8944_PDATA_H__

#define WM8944_NUM_LDO   1
#define WM8944_NUM_GPIO  2

enum wm8944_vmid_mode {
	WM8944_VMID_FAST=1,
	WM8944_VMID_NORMAL,
	WM8944_VMID_SLOW,
};

struct wm8944_ldo_pdata {
	/** GPIOs to enable regulator, 0 or less if not available */
	int enable;

	const struct regulator_init_data *init_data;
};

#define WM8944_CONFIGURE_GPIO 0x10000

#define WM8944_DRC_REGS 7
#define WM8944_EQ_REGS  43

/**
 * DRC configurations are specified with a label and a set of register
 * values to write (the enable bits will be ignored).  At runtime an
 * enumerated control will be presented for each DRC block allowing
 * the user to choose the configration to use.
 *
 * Configurations may be generated by hand or by using the DRC control
 * panel provided by the WISCE - see  http://www.wolfsonmicro.com/wisce/
 * for details.
 */
struct wm8944_drc_cfg {
        const char *name;
        u16 regs[WM8944_DRC_REGS];
};

/**
 * ReTune Mobile configurations are specified with a label, sample
 * rate and set of values to write (the enable bits will be ignored).
 *
 * Configurations are expected to be generated using the ReTune Mobile
 * control panel in WISCE - see http://www.wolfsonmicro.com/wisce/
 */
struct wm8944_retune_mobile_cfg {
        const char *name;
        unsigned int rate;
        u16 regs[WM8944_EQ_REGS];
};

/**
 * Multiband compressor configurations are specified with a label and
 * two sets of values to write.  Configurations are expected to be
 * generated using the multiband compressor configuration panel in
 * WISCE - see http://www.wolfsonmicro.com/wisce/
 */

struct wm8944_pdata {
	int gpio_base;

	/**
	 * Default values for GPIOs if non-zero, WM8944_CONFIGURE_GPIO
	 * can be used for all zero values.
	 */
	int gpio_defaults[WM8944_NUM_GPIO];

	struct wm8944_ldo_pdata ldo[WM8944_NUM_LDO];

	int irq_base;  /** Base IRQ number for WM8944, required for IRQs */

	int num_drc_cfgs;
	struct wm8944_drc_cfg *drc_cfgs;

	int num_retune_mobile_cfgs;
	struct wm8944_retune_mobile_cfg *retune_mobile_cfgs;

	/* Vref to analogue output resistance */
#define WM8944_VROI_20K 0
#define WM8944_VROI_1Kx 1
	unsigned int line_vroi:1;
	unsigned int spk_vroi:1;

	/* WM8944 microphone biases: 0=0.9*LDOVOUT 1=0.65*LDOVOUT */
	unsigned int micbias_lvl:1;

	/*
	 * SPKMODE must be pulled internally by the device on this
	 * system.
	 */
	bool spkmode_pu;

	enum wm8944_vmid_mode vmid_mode;
};

#endif
